// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDg9NHPfkYCTdEqRvdtJcjHuoxIrDJfU0',
    appId: '1:450810469081:web:f0eb846cb652800020fcc8',
    messagingSenderId: '450810469081',
    projectId: 'clone-5606a',
    authDomain: 'clone-5606a.firebaseapp.com',
    storageBucket: 'clone-5606a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4bWV6VI00Gmtj6I64a4-uMLXiUm5Xe20',
    appId: '1:450810469081:android:1c3630cff737dab920fcc8',
    messagingSenderId: '450810469081',
    projectId: 'clone-5606a',
    storageBucket: 'clone-5606a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIePffxN8kixxDqvyKNm5Lw-CvHcXHf4k',
    appId: '1:450810469081:ios:81374d1673567af220fcc8',
    messagingSenderId: '450810469081',
    projectId: 'clone-5606a',
    storageBucket: 'clone-5606a.firebasestorage.app',
    iosBundleId: 'com.example.amazonClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIePffxN8kixxDqvyKNm5Lw-CvHcXHf4k',
    appId: '1:450810469081:ios:81374d1673567af220fcc8',
    messagingSenderId: '450810469081',
    projectId: 'clone-5606a',
    storageBucket: 'clone-5606a.firebasestorage.app',
    iosBundleId: 'com.example.amazonClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDg9NHPfkYCTdEqRvdtJcjHuoxIrDJfU0',
    appId: '1:450810469081:web:66ca22498bc8721a20fcc8',
    messagingSenderId: '450810469081',
    projectId: 'clone-5606a',
    authDomain: 'clone-5606a.firebaseapp.com',
    storageBucket: 'clone-5606a.firebasestorage.app',
  );
}
